# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wholegui2.ui'
#
# Created: Mon Jul 28 14:26:01 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 651)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton_ServerConnect = QtGui.QPushButton(self.centralWidget)
        self.pushButton_ServerConnect.setGeometry(QtCore.QRect(210, 20, 200, 71))
        self.pushButton_ServerConnect.setObjectName("pushButton_ServerConnect")
        self.lineEdit_Username = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_Username.setGeometry(QtCore.QRect(70, 30, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.lineEdit_Username.setFont(font)
        self.lineEdit_Username.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_Username.setText("")
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(70, 60, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setInputMask("")
        self.lineEdit_Password.setText("")
        self.lineEdit_Password.setMaxLength(32767)
        self.lineEdit_Password.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.label_AvailableProjects = QtGui.QLabel(self.centralWidget)
        self.label_AvailableProjects.setGeometry(QtCore.QRect(20, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_AvailableProjects.setFont(font)
        self.label_AvailableProjects.setObjectName("label_AvailableProjects")
        self.pushButton_GetProjects = QtGui.QPushButton(self.centralWidget)
        self.pushButton_GetProjects.setGeometry(QtCore.QRect(235, 110, 150, 32))
        self.pushButton_GetProjects.setObjectName("pushButton_GetProjects")
        self.pushButton_ProjectConnect = QtGui.QPushButton(self.centralWidget)
        self.pushButton_ProjectConnect.setGeometry(QtCore.QRect(235, 260, 150, 32))
        self.pushButton_ProjectConnect.setObjectName("pushButton_ProjectConnect")
        self.listWidget_Projects = QtGui.QListWidget(self.centralWidget)
        self.listWidget_Projects.setGeometry(QtCore.QRect(20, 140, 421, 111))
        self.listWidget_Projects.setObjectName("listWidget_Projects")
        self.pushButton_ReqSearch = QtGui.QPushButton(self.centralWidget)
        self.pushButton_ReqSearch.setGeometry(QtCore.QRect(30, 300, 401, 41))
        self.pushButton_ReqSearch.setCheckable(False)
        self.pushButton_ReqSearch.setObjectName("pushButton_ReqSearch")
        self.pushButton_taskSearch = QtGui.QPushButton(self.centralWidget)
        self.pushButton_taskSearch.setGeometry(QtCore.QRect(30, 530, 401, 41))
        self.pushButton_taskSearch.setObjectName("pushButton_taskSearch")
        self.pushButton_tcSearch = QtGui.QPushButton(self.centralWidget)
        self.pushButton_tcSearch.setGeometry(QtCore.QRect(30, 580, 401, 41))
        self.pushButton_tcSearch.setObjectName("pushButton_tcSearch")
        self.listWidget_Reqs = QtGui.QListWidget(self.centralWidget)
        self.listWidget_Reqs.setGeometry(QtCore.QRect(20, 340, 421, 141))
        self.listWidget_Reqs.setObjectName("listWidget_Reqs")
        self.pushButton_lookUpReq = QtGui.QPushButton(self.centralWidget)
        self.pushButton_lookUpReq.setGeometry(QtCore.QRect(320, 490, 114, 32))
        self.pushButton_lookUpReq.setObjectName("pushButton_lookUpReq")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 461, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_Username, self.lineEdit_Password)
        MainWindow.setTabOrder(self.lineEdit_Password, self.pushButton_ServerConnect)
        MainWindow.setTabOrder(self.pushButton_ServerConnect, self.pushButton_GetProjects)
        MainWindow.setTabOrder(self.pushButton_GetProjects, self.listWidget_Projects)
        MainWindow.setTabOrder(self.listWidget_Projects, self.pushButton_ProjectConnect)
        MainWindow.setTabOrder(self.pushButton_ProjectConnect, self.pushButton_ReqSearch)
        MainWindow.setTabOrder(self.pushButton_ReqSearch, self.listWidget_Reqs)
        MainWindow.setTabOrder(self.listWidget_Reqs, self.pushButton_lookUpReq)
        MainWindow.setTabOrder(self.pushButton_lookUpReq, self.pushButton_taskSearch)
        MainWindow.setTabOrder(self.pushButton_taskSearch, self.pushButton_tcSearch)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ServerConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect To Server", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Username.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Password.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_AvailableProjects.setText(QtGui.QApplication.translate("MainWindow", "Available Projects:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_GetProjects.setText(QtGui.QApplication.translate("MainWindow", "Get All Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ProjectConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect To Project", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ReqSearch.setText(QtGui.QApplication.translate("MainWindow", "Search for Requirements", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_taskSearch.setText(QtGui.QApplication.translate("MainWindow", "Search for Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tcSearch.setText(QtGui.QApplication.translate("MainWindow", "Search for Test Cases", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_lookUpReq.setText(QtGui.QApplication.translate("MainWindow", "More...", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "SpiraGUI", None, QtGui.QApplication.UnicodeUTF8))

